#!/bin/bash

##################################
## set mouse speed for libinput ##
##################################

# detect connected mouse devices
IDS=$(xinput | grep -o 'id=[0-9]*' | grep -o '[0-9]*')
echo "generating mouse IDS"
[ -e /tmp/mouse ] && rm /tmp/mouse
while read -r line; do
    if xinput list-props "$line" | grep -q 'libinput Accel Speed'; then
        xinput set-prop "$line" "libinput Accel Speed" "${1:--0.195000}"
    fi
done <<<"$IDS"

