image: Visual Studio 2017

configuration:
  - Release

before_build:
  nuget restore src\DotfilesWrapper\DotfilesWrapper -SolutionDirectory src\DotfilesWrapper

build:
  parallel: true
  project: src\DotfilesWrapper\DotfilesWrapper.sln
  publish_nuget: true
  verbosity: normal

after_build:
  7z a dotfiles.zip .\src\DotfilesWrapper\DotfilesWrapper\bin\Release\*.exe .\src\DotfilesWrapper\DotfilesWrapper\bin\Release\*.dll .\src\templates\*.yaml .\src\scripts\*.ps1 .\src\configs\*

artifacts:
  - path: dotfiles.zip
    name: dotfiles

deploy:
  release: dotfiles-$(APPVEYOR_REPO_TAG_NAME)
  description: 'dotfiles $(APPVEYOR_REPO_TAG_NAME) release.'
  provider: GitHub
  auth_token:
    secure: oi4DXySv0pePN3v3N6LG83wlrbAHRFulTec/9hJ5+GMtjbLwoxurPHagYEsS1lzD
  tag: $(APPVEYOR_REPO_TAG_NAME)
  artifact: dotfiles.zip
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
