variables:
  CI: 'true'

jobs:
  - job: DotNet
    pool:
      vmImage: 'windows-latest'
    steps:
      - powershell: |
          $downloadLocation = [System.IO.Path]::GetTempPath() + "dotfiles"
          Invoke-Expression ((new-object net.webclient).downloadstring("https://raw.githubusercontent.com/DiXN/dotfiles/master/src/scripts/download-repo.ps1"))
          dotnet tool install -g dotnet-script
          Invoke-Expression ("${env:userprofile}\.dotnet\tools\dotnet-script.exe -c release $downloadLocation\scripts\dotnet\main.csx")
  - job: Dotfiles
    dependsOn: DotNet
    condition: succeeded()
    timeoutInMinutes: 200
    pool:
      vmImage: 'win1803'
    steps:
      - powershell: .\src\scripts\init.ps1
        displayName: Run `init.ps1`
        env:
          CI: 'true'
