trigger:
  - master
  - linux
  - chezmoi

variables:
  CI: 'true'
  INST_USER: 'mk'

jobs:
  - job: arch
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          docker run -d -it -v $PWD:/dot --name "arch" archlinux:latest
          docker exec -e INST_USER=$(INST_USER) arch /bin/bash "/dot/ci.sh"
        displayName: setup user
      - bash: docker exec -u ${INST_USER} arch /bin/bash -c "/dot/src/scripts/init.sh"
        displayName: initializing dotfiles
      - bash: docker exec -u ${INST_USER} arch /bin/bash -c "/dot/linux/essentials.sh"
        displayName: finalizing dotfiles

