copy_on_select yes
enable_audio_bell no
sync_to_monitor yes
background_opacity 0.9
background #3c3d4b
font_familiy Fira Code Nerd Font Mono'
font_size 12
mouse_enabled yes

startup_session launch.conf
